### ISSUE TITLE
NOOBS 0.2.2 OSMC Pi 3

### ISSUE THREAD

**Issue by vgoffman** [matthuisman/kodi-repo#1]
Hi I cant install to my OSMC for my Raspberry Pi 3 Recalbox with games. The NOOBS repo installed from zip file but when I am opening it I have an error:

08:40:33.936 T:1958481920   DEBUG: ------ Window Init (MyPrograms.xml) ------
08:40:34.029 T:1958481920   ERROR: Control 55 in window 10001 has been asked to focus, but it can't
08:40:34.067 T:1958481920   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.program.noobs.companion/)
08:40:34.068 T:1958481920   DEBUG:   ParentPath = [plugin://plugin.program.noobs.companion/]
08:40:34.169 T:1614795760   DEBUG: CAddonDatabase::SetLastUsed[plugin.program.noobs.companion] took 102 ms
08:40:34.169 T:1937765360   DEBUG: Thread JobWorker start, auto delete: true
08:40:34.170 T:1772090352   DEBUG: StartScript - calling plugin NOOBS Companion('plugin://plugin.program.noobs.companion/','3','')
08:40:34.170 T:1592783856   DEBUG: Thread LanguageInvoker start, auto delete: false
08:40:34.170 T:1592783856    INFO: initializing python engine.
08:40:34.170 T:1592783856   DEBUG: CPythonInvoker(5, /home/osmc/.kodi/addons/plugin.program.noobs.companion/addon.py): start processing
08:40:34.570 T:1958481920   DEBUG: ------ Window Init (DialogBusy.xml) ------
08:40:34.622 T:1592783856   DEBUG: -->Python Interpreter Initialized<--
08:40:34.623 T:1592783856   DEBUG: CPythonInvoker(5, /home/osmc/.kodi/addons/plugin.program.noobs.companion/addon.py): the source file to load is "/home/osmc/.kodi/addons/plugin.program.noobs.companion/addon.py"
08:40:34.623 T:1592783856   DEBUG: CPythonInvoker(5, /home/osmc/.kodi/addons/plugin.program.noobs.companion/addon.py): setting the Python path to /home/osmc/.kodi/addons/plugin.program.noobs.companion:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
08:40:34.623 T:1592783856   DEBUG: CPythonInvoker(5, /home/osmc/.kodi/addons/plugin.program.noobs.companion/addon.py): entering source directory /home/osmc/.kodi/addons/plugin.program.noobs.companion
08:40:34.623 T:1592783856   DEBUG: CPythonInvoker(5, /home/osmc/.kodi/addons/plugin.program.noobs.companion/addon.py): instantiating addon using automatically obtained id of "plugin.program.noobs.companion" dependent on version 2.14.0 of the xbmc.python api
08:40:35.208 T:1592783856   DEBUG: sudo su -c 'chmod +x /home/osmc/.kodi/addons/plugin.program.noobs.companion/resources/files/part_reboot'
08:40:35.341 T:1592783856   DEBUG: sudo su -c 'mkdir -p /tmp/mount && mount -o ro /dev/mmcblk0p5 /tmp/mount'
08:40:35.497 T:1592783856   DEBUG: sudo su -c 'umount /tmp/mount && rmdir /tmp/mount'
08:40:35.768 T:1592783856   DEBUG: Previous line repeats 1 times.
08:40:35.768 T:1592783856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No such file or directory: '/tmp/mount/installed_os.json'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.program.noobs.companion/addon.py", line 155, in <module>
                                                util.init()
                                              File "/home/osmc/.kodi/addons/plugin.program.noobs.companion/resources/lib/util.py", line 121, in init
                                                _build_systems()
                                              File "/home/osmc/.kodi/addons/plugin.program.noobs.companion/resources/lib/util.py", line 131, in _build_systems
                                                with open(os.path.join(settings_path, 'installed_os.json')) as f:
                                            IOError: [Errno 2] No such file or directory: '/tmp/mount/installed_os.json'
                                            -->End of Python script error report<--
08:40:35.787 T:1958481920   DEBUG: ------ Window Init (DialogNotification.xml) ------
08:40:35.871 T:1592783856    INFO: Python script stopped
08:40:35.871 T:1592783856   DEBUG: Thread LanguageInvoker 1592783856 terminating
08:40:35.888 T:1958481920   ERROR: GetDirectory - Error getting plugin://plugin.program.noobs.companion/
08:40:35.888 T:1958481920   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.noobs.companion/) failed
08:40:35.888 T:1958481920   DEBUG: CGUIMediaWindow::GetDirectory ()
08:40:35.888 T:1958481920   DEBUG:   ParentPath = [plugin://plugin.program.noobs.companion/]
08:40:35.984 T:1592783856   DEBUG: Thread BackgroundLoader start, auto delete: false
08:40:35.987 T:1592783856   DEBUG: Thread BackgroundLoader 1592783856 terminating
08:40:36.046 T:1958481920   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
08:40:38.178 T:1830810608   DEBUG: script.module.osmcsetting.updates :  - blurp 485 - MyPrograms.xml
08:40:41.528 T:1958481920   DEBUG: ------ Window Deinit (DialogNotification.xml) ------

**Comment by matthuisman** [comment]
Think I have found the issue :)
I'll upload a new version to try soon

**Comment by vgoffman** [comment]
That’s great! Please let me know when you upload new version. Thanks!

**Comment by matthuisman** [comment]
@vgoffman 

Could you give this ZIP a test before I push it as an update:
https://drive.google.com/open?id=1Zwlz5rkBduTFFtzniKlk_Esvft_AkLmO

**Comment by vgoffman** [comment]
ERROR: Failed to read 'zip://kodi-repo-master.zip/kodi-repo-master/addon.xml'
09:27:26.994 T:1302328304   ERROR: Previous line repeats 1 times.

**Comment by matthuisman** [comment]
That error is unrelated to my add-on.
Please only paste full debug logs.

**Comment by vgoffman** [comment]
00:14:00.739 T:1958236160  NOTICE: special://profile/ is mapped to: special://masterprofile/
00:14:00.740 T:1958236160  NOTICE: -----------------------------------------------------------------------
00:14:00.740 T:1958236160  NOTICE: Starting Kodi (17.5). Platform: Linux ARM (Thumb) 32-bit
00:14:00.740 T:1958236160  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
00:14:00.740 T:1958236160  NOTICE: Kodi compiled Oct 29 2017 by GCC 4.9.2 for Linux ARM (Thumb) 32-bit version 3.16.39 (200743)
00:14:00.740 T:1958236160  NOTICE: Running on Open Source Media Center 2017.10-1, kernel: Linux ARM 32-bit version 4.9.29-10-osmc
00:14:00.750 T:1958236160  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
00:14:00.750 T:1958236160  NOTICE: Host CPU: ARMv7 Processor rev 4 (v7l), 4 cores available
00:14:00.750 T:1958236160  NOTICE: ARM Features: Neon disabled
00:14:00.750 T:1958236160  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
00:14:00.750 T:1958236160  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
00:14:00.750 T:1958236160  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
00:14:00.750 T:1958236160  NOTICE: special://masterprofile/ is mapped to: /home/osmc/.kodi/userdata
00:14:00.750 T:1958236160  NOTICE: special://envhome/ is mapped to: /home/osmc
00:14:00.750 T:1958236160  NOTICE: special://home/ is mapped to: /home/osmc/.kodi
00:14:00.751 T:1958236160  NOTICE: special://temp/ is mapped to: /home/osmc/.kodi/temp
00:14:00.751 T:1958236160  NOTICE: special://logpath/ is mapped to: /home/osmc/.kodi/temp
00:14:00.751 T:1958236160  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
00:14:00.751 T:1958236160  NOTICE: Local hostname: EraLim-TV
00:14:00.751 T:1958236160  NOTICE: Log File is located: /home/osmc/.kodi/temp//kodi.log
00:14:00.751 T:1958236160  NOTICE: -----------------------------------------------------------------------
00:14:00.873 T:1958236160   ERROR: DBus: Error org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
00:14:00.957 T:1958236160  NOTICE: load settings...
00:14:01.246 T:1958236160  NOTICE: Found 2 Lists of Devices
00:14:01.247 T:1958236160  NOTICE: Enumerated PI devices:
00:14:01.247 T:1958236160  NOTICE:     Device 1
00:14:01.247 T:1958236160  NOTICE:         m_deviceName      : HDMI
00:14:01.247 T:1958236160  NOTICE:         m_displayName     : HDMI
00:14:01.247 T:1958236160  NOTICE:         m_displayNameExtra:
00:14:01.247 T:1958236160  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
00:14:01.247 T:1958236160  NOTICE:         m_channels        : FL,FR
00:14:01.247 T:1958236160  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
00:14:01.247 T:1958236160  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP,AE_FMT_RAW
00:14:01.247 T:1958236160  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_EAC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_512
00:14:01.247 T:1958236160  NOTICE:     Device 2
00:14:01.248 T:1958236160  NOTICE:         m_deviceName      : Analogue
00:14:01.248 T:1958236160  NOTICE:         m_displayName     : Analogue
00:14:01.248 T:1958236160  NOTICE:         m_displayNameExtra:
00:14:01.248 T:1958236160  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
00:14:01.248 T:1958236160  NOTICE:         m_channels        : FL,FR
00:14:01.248 T:1958236160  NOTICE:         m_sampleRates     : 48000
00:14:01.248 T:1958236160  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
00:14:01.248 T:1958236160  NOTICE:         m_streamTypes     : No passthrough capabilities
00:14:01.248 T:1958236160  NOTICE:     Device 3
00:14:01.248 T:1958236160  NOTICE:         m_deviceName      : Both
00:14:01.248 T:1958236160  NOTICE:         m_displayName     : HDMI and Analogue
00:14:01.248 T:1958236160  NOTICE:         m_displayNameExtra:
00:14:01.248 T:1958236160  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
00:14:01.249 T:1958236160  NOTICE:         m_channels        : FL,FR
00:14:01.249 T:1958236160  NOTICE:         m_sampleRates     : 48000
00:14:01.249 T:1958236160  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_FLOATP,AE_FMT_S32NEP,AE_FMT_S16NEP
00:14:01.249 T:1958236160  NOTICE:         m_streamTypes     : No passthrough capabilities
00:14:01.249 T:1958236160  NOTICE: Enumerated ALSA devices:
00:14:01.249 T:1958236160  NOTICE:     Device 1
00:14:01.249 T:1958236160  NOTICE:         m_deviceName      : @
00:14:01.249 T:1958236160  NOTICE:         m_displayName     : Default (bcm2835 ALSA bcm2835 ALSA)
00:14:01.249 T:1958236160  NOTICE:         m_displayNameExtra:
00:14:01.249 T:1958236160  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
00:14:01.249 T:1958236160  NOTICE:         m_channels        : FL,FR
00:14:01.249 T:1958236160  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,32000,44100,48000
00:14:01.249 T:1958236160  NOTICE:         m_dataFormats     : AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_U8
00:14:01.249 T:1958236160  NOTICE:         m_streamTypes     : No passthrough capabilities
00:14:01.287 T:1958236160  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
00:14:01.287 T:1958236160  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            
                                            
                                            
                                            <advancedsettings>
                                              <imageres>540</imageres>
                                              <fanartres>720</fanartres>
                                              <splash>false</splash>
                                              <handlemounting>0</handlemounting>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                            </advancedsettings>
00:14:01.291 T:1958236160  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
00:14:01.291 T:1958236160  NOTICE: Default Video Player: VideoPlayer
00:14:01.291 T:1958236160  NOTICE: Default Audio Player: paplayer
00:14:01.291 T:1958236160  NOTICE: Disabled debug logging due to GUI setting. Level 0.
00:14:01.291 T:1958236160  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
00:14:01.302 T:1958236160  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
00:14:01.306 T:1958236160  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
00:14:01.309 T:1958236160  NOTICE: Loaded playercorefactory configuration
00:14:01.309 T:1958236160  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
00:14:01.310 T:1958236160  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
00:14:02.257 T:1958236160  NOTICE: Running database version Addons27
00:14:04.791 T:1958236160  NOTICE: ADDONS: Using repository repository.xbmc.org
00:14:04.791 T:1958236160  NOTICE: ADDONS: Using repository repository.search.db
00:14:29.326 T:1958236160  NOTICE: Raspberry PI firmware version: Sep 22 2017 21:36:43 
                                            Copyright (c) 2012 Broadcom
                                            version f5217b8887607d0dd890a434de9c73d9aa9a7c0f (clean) (release)
00:14:29.326 T:1958236160  NOTICE: ARM mem: 768MB GPU mem: 256MB MPG2:0 WVC1:0
00:14:29.326 T:1958236160  NOTICE: cache.memorysize: 20MB libass.cache: 0MB
00:14:29.326 T:1958236160  NOTICE: Config:
                                            arm_freq=1200
                                            audio_pwm_mode=1
                                            config_hdmi_boost=5
                                            core_freq=400
                                            desired_osc_freq=0x36ee80
                                            disable_commandline_tags=2
                                            disable_l2cache=1
                                            disable_splash=1
                                            force_eeprom_read=1
                                            force_pwm_open=1
                                            framebuffer_ignore_alpha=1
                                            framebuffer_swap=1
                                            gpu_freq=300
                                            hdmi_channel_map=8
                                            hdmi_force_cec_address=65535
                                            hdmi_ignore_cec_init=1
                                            init_uart_clock=0x2dc6c00
                                            lcd_framerate=60
                                            over_voltage_avs=0x13d62
                                            over_voltage_avs_boost=0x13d62
                                            pause_burst_frames=1
                                            program_serial_random=1
                                            sdram_freq=450
                                            temp_limit=85
00:14:29.327 T:1958236160  NOTICE: Config:
                                            device_tree=-
00:14:29.342 T:1958236160  NOTICE: InitWindowSystem: Using EGL Implementation: raspberrypi
00:14:29.345 T:1958236160  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 60.000000 Hz
00:14:29.345 T:1958236160  NOTICE: Found resolution 640 x 480 for display 0 with 640 x 480 @ 59.940063 Hz
00:14:29.345 T:1958236160  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 60.000000 Hz
00:14:29.345 T:1958236160  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 59.940063 Hz
00:14:29.345 T:1958236160  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000000 Hz
00:14:29.345 T:1958236160  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 59.940063 Hz
00:14:29.345 T:1958236160  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
00:14:29.345 T:1958236160  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.940063 Hz
00:14:29.345 T:1958236160  NOTICE: Found (1280x720@60.000000) at 20, setting to RES_DESKTOP at 16
00:14:29.346 T:1958236160  NOTICE: Checking resolution 16
00:14:29.645 T:1958236160  NOTICE: GL_VENDOR = Broadcom
00:14:29.645 T:1958236160  NOTICE: GL_RENDERER = VideoCore IV HW
00:14:29.645 T:1958236160  NOTICE: GL_VERSION = OpenGL ES 2.0
00:14:29.645 T:1958236160  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
00:14:29.645 T:1958236160  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_APPLE_rgb_422 GL_EXT_debug_marker
00:14:32.057 T:1830810608  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
00:14:32.076 T:1937765360  NOTICE: Running database version Addons27
00:14:32.080 T:1937765360  NOTICE: Running database version ViewModes6
00:14:32.085 T:1937765360  NOTICE: Running database version Textures13
00:14:32.105 T:1937765360  NOTICE: Running database version MyMusic60
00:14:32.135 T:1937765360  NOTICE: Running database version MyVideos107
00:14:32.206 T:1937765360  NOTICE: Running database version TV29
00:14:32.215 T:1937765360  NOTICE: Running database version Epg11
00:14:32.225 T:1958236160  NOTICE: start dvd mediatype detection
00:14:34.455 T:1958236160 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
00:14:34.783 T:1958236160 WARNING: CApplication::Initialize - startup.xml taints init process
00:14:34.840 T:1958236160  NOTICE: UpdateLibraries: Starting video library startup scan
00:14:34.951 T:1685185520  NOTICE: VideoInfoScanner: Starting scan ..
00:14:34.986 T:1958236160  NOTICE: initialize done
00:14:34.986 T:1958236160  NOTICE: Running the application...
00:14:35.214 T:1937765360  NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 291 channels.
00:14:41.127 T:1958236160 WARNING: Skin has invalid include: skinshortcuts-template-home-submenu-widget
00:14:42.062 T:1958236160  NOTICE: starting zeroconf publishing
00:14:42.064 T:1958236160  NOTICE: CWebServer[80]: Started
00:14:42.064 T:1958236160  NOTICE: starting upnp client
00:14:42.238 T:1553986544  NOTICE: ES: Starting UDP Event server on port 9777
00:14:42.238 T:1553986544  NOTICE: UDP: Listening on port 9777 (ipv6 : true)
00:14:43.464 T:1958236160  NOTICE: CVideoPlayer::CloseFile()
00:14:43.464 T:1958236160  NOTICE: VideoPlayer: waiting for threads to exit
00:14:43.464 T:1958236160  NOTICE: VideoPlayer: finished waiting
00:14:43.465 T:1958236160  NOTICE: CVideoPlayer::CloseFile()
00:14:43.465 T:1958236160  NOTICE: VideoPlayer: waiting for threads to exit
00:14:43.465 T:1958236160  NOTICE: VideoPlayer: finished waiting
00:14:45.390 T:1685185520  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:10
00:14:48.630 T:1667863536  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.5), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
00:14:50.835 T:1937765360  NOTICE: Start - EPG thread started
00:15:01.260 T:1481630704  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
00:15:09.777 T:1398797296  NOTICE: Skin Helper Service --> Starting WebService on port 52307
00:15:09.780 T:1701962736  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.23.026 started
00:15:29.406 T:1735517168 WARNING: CSkinInfo: failed to load skin settings
00:15:49.213 T:1958236160   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
00:15:49.214 T:1958236160 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
00:15:50.518 T:1958236160   ERROR: Failed to read 'zip://http%3a%2f%2ftv.eralim.com%2frepo%2fkodi-repo-master.zip/kodi-repo-master/addon.xml'

**Comment by matthuisman** [comment]
That is not my addon or repo (http://tv.eralim.com/repo/kodi-repo-master.zip/kodi-repo-master/addon.xml)
Your obviously using some banned addon's that often cause incompatibilities / stuff a bunch of stuff up.

Start with a FRESH install of LibreELEC / OSMC, then install my add-on.
If it still fails, open a new issue with a full debug log (use pastebin instead of pasting here).

Closing Issue.

**Comment by vgoffman** [comment]
this is your repo. i downloaded zip file to my host

**Comment by vgoffman** [comment]
I am using fresh and clean OSMC and installing your repo i downloaded from github and upload it to my host.

**Comment by matthuisman** [comment]
Well your doing something wrong.

It's failing to download this file:
http://tv.eralim.com/repo/kodi-repo-master.zip/kodi-repo-master/addon.xml

I'll only respond to ERRORs that are actually from within my add-on.
(Last the first ERROR you posted)

**Comment by vgoffman** [comment]
Can you please provide correct repo address? I will try to install a zip file from you repo

**Comment by matthuisman** [comment]
http://kodi.matthuisman.nz/repository.matthuisman.zip
